services:
  openchamber:
    build:
      context: .
      dockerfile: Dockerfile
    image: openchamber:local
    container_name: openchamber
    ports:
      - "${PORT:-3000}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/suraj/openchamber/openchamber:/home/openchamber/.config/openchamber
      - /home/suraj/openchamber/opencode/share:/home/openchamber/.local/share/opencode
      - /home/suraj/openchamber/opencode/state:/home/openchamber/.local/state/opencode
      - /home/suraj/openchamber/opencode/config:/home/openchamber/.config/opencode
      - /home/suraj/openchamber/ssh:/home/openchamber/.ssh
      - /home/suraj/projects:/home/openchamber/workspaces
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - UI_PASSWORD=${UI_PASSWORD}
      - CF_TUNNEL=${CF_TUNNEL}
      - OH_MY_OPENCODE=${OH_MY_OPENCODE}
      - OPENCODE_HOST=${OPENCODE_HOST}
      - OPENCODE_SKIP_START=${OPENCODE_SKIP_START}
    restart: unless-stopped
